name: Testing

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'docs/**'
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  call-regression-test:
    name: "Regression test"
    uses: xenanetworks/xoa-regression-tests/.github/workflows/execute-test-suite-denmark-tester.yml@main
    secrets: inherit

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
