name: Check if test suite workable

on:
  push:
    branches:
     - "**"
  pull_request:
    branches:
     - "**"

jobs:
  call-regression-test:
    uses: xenanetworks/xoa-regression-tests/.github/workflows/execute-test-suite-denmark-tester.yml@main
    secrets: inherit

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true